import React, { useState, useEffect, useRef } from "react";
import Navbar from "./Navbar";
import Footer from "./footer";
import { GuaranteedSpot } from "../types/user";
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

type User = {
  name: string;
  intra: string;
  verified: boolean;
  created_at: string;
  rating?: number;
};

type Team = {
  name: string;
  players: User[];
};

const Teams: React.FC = () => {
  const [registeredUsers, setRegisteredUsers] = useState<User[]>([]);
  const [availablePlayers, setAvailablePlayers] = useState<User[]>([]);
  const [waitingListPlayers, setWaitingListPlayers] = useState<User[]>([]);
  const [team1, setTeam1] = useState<Team>({ name: "Team 1", players: [] });
  const [team2, setTeam2] = useState<Team>({ name: "Team 2", players: [] });
  const [team3, setTeam3] = useState<Team>({ name: "Team 3", players: [] });
  const [removedPlayers, setRemovedPlayers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [draggedPlayer, setDraggedPlayer] = useState<User | null>(null);
  const [dragSource, setDragSource] = useState<'available' | 'team1' | 'team2' | 'team3' | null>(null);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetch("/api/users")
      .then((response) => response.json())
      .then((data) => {
        if (Array.isArray(data)) {
          const eligiblePlayers = data.slice(0, GuaranteedSpot).map(user => ({ ...user, rating: 1 }));
          const waitingPlayers = data.slice(GuaranteedSpot);

          setRegisteredUsers(data);
          setAvailablePlayers(eligiblePlayers);
          setWaitingListPlayers(waitingPlayers);
          setLoading(false);
        }
      })
      .catch((error) => {
        console.error("Error fetching registered users:", error);
        setRegisteredUsers([]);
        setAvailablePlayers([]);
        setWaitingListPlayers([]);
        setLoading(false);
      });
  }, []);

  // Close export menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (showExportMenu) {
        const target = event.target as HTMLElement;
        if (!target.closest('.export-dropdown')) {
          setShowExportMenu(false);
        }
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showExportMenu]);

  // Export functions
  const exportToPDF = async () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageHeight = 297;
    const pageWidth = 210;
    let yPosition = 20;

    // Title
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('⚽ Football Teams Roster', pageWidth / 2, yPosition, { align: 'center' });
    
    yPosition += 15;
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
    
    yPosition += 20;

    const teams = [
      { team: team1, color: [0, 122, 188] }, // Blue
      { team: team2, color: [0, 128, 126] }, // Teal
      { team: team3, color: [40, 167, 69] }  // Green
    ];

    teams.forEach((teamData) => {
      if (yPosition > pageHeight - 60) {
        pdf.addPage();
        yPosition = 20;
      }

      // Team header with background
      pdf.setFillColor(teamData.color[0], teamData.color[1], teamData.color[2]);
      pdf.rect(20, yPosition - 8, pageWidth - 40, 12, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text(teamData.team.name, 25, yPosition, { baseline: 'middle' });
      
      const avgRating = teamData.team.players.length > 0 
        ? (teamData.team.players.reduce((sum, p) => sum + (p.rating || 1), 0) / teamData.team.players.length).toFixed(1)
        : '0';
      pdf.text(`Players: ${teamData.team.players.length}/7 | Avg Rating: ${avgRating}`, pageWidth - 25, yPosition, { align: 'right', baseline: 'middle' });
      
      yPosition += 15;
      pdf.setTextColor(0, 0, 0);

      // Players list
      if (teamData.team.players.length === 0) {
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'italic');
        pdf.text('No players assigned', 25, yPosition);
        yPosition += 8;
      } else {
        teamData.team.players.forEach((player, index) => {
          pdf.setFontSize(12);
          pdf.setFont('helvetica', 'normal');
          
          const stars = '★'.repeat(player.rating || 1) + '☆'.repeat(5 - (player.rating || 1));
          pdf.text(`${index + 1}. ${player.name} (${player.intra}) - ${stars}`, 25, yPosition);
          yPosition += 6;
        });
      }
      
      yPosition += 10;
    });

    // Footer
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    pdf.text('Generated by 42 Football Club Management System', pageWidth / 2, pageHeight - 10, { align: 'center' });

    pdf.save('football-teams.pdf');
  };

  const exportToImage = async (format: 'png' | 'jpeg' = 'png') => {
    if (!exportRef.current) return;

    try {
      // Create a temporary container for export
      const exportContainer = document.createElement('div');
      exportContainer.style.position = 'absolute';
      exportContainer.style.left = '-9999px';
      exportContainer.style.width = '1200px';
      exportContainer.style.background = 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)';
      exportContainer.style.color = 'white';
      exportContainer.style.fontFamily = 'Arial, sans-serif';
      exportContainer.style.padding = '40px';
      
      const teams = [team1, team2, team3];
      const teamColors = ['#007abc', '#00807e', '#28a745'];
      
      exportContainer.innerHTML = `
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="margin: 0; font-size: 48px; text-shadow: 2px 2px 4px rgba(0,0,0,0.5);">⚽ Football Teams</h1>
          <p style="margin: 10px 0 0 0; font-size: 18px; opacity: 0.9;">Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 30px;">
          ${teams.map((team) => `
            <div style="background: rgba(255,255,255,0.1); border-radius: 15px; padding: 25px; backdrop-filter: blur(10px);">
              <h2 style="margin: 0 0 20px 0; font-size: 24px; text-align: center; color: ${teamColors[teams.indexOf(team)]}; text-shadow: 1px 1px 2px rgba(0,0,0,0.7);">${team.name}</h2>
              <div style="text-align: center; margin-bottom: 15px; font-size: 14px; opacity: 0.8;">
                Players: ${team.players.length}/7 | Avg Rating: ${team.players.length > 0 ? (team.players.reduce((sum, p) => sum + (p.rating || 1), 0) / team.players.length).toFixed(1) : '0'}
              </div>
              ${team.players.length === 0 ? 
                '<p style="text-align: center; font-style: italic; opacity: 0.7;">No players assigned</p>' : 
                team.players.map((player, playerIndex) => `
                  <div style="margin: 8px 0; padding: 8px; background: rgba(255,255,255,0.05); border-radius: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <span style="font-weight: bold;">${playerIndex + 1}. ${player.name}</span>
                    <span style="font-size: 12px; opacity: 0.8;">${'★'.repeat(player.rating || 1)}${'☆'.repeat(5 - (player.rating || 1))}</span>
                  </div>
                `).join('')
              }
            </div>
          `).join('')}
        </div>
        <div style="text-align: center; margin-top: 30px; font-size: 12px; opacity: 0.7;">
          Generated by 42 Football Club Management System
        </div>
      `;
      
      document.body.appendChild(exportContainer);

      const canvas = await html2canvas(exportContainer, {
        backgroundColor: null,
        scale: 2,
        logging: false,
        useCORS: true
      });

      document.body.removeChild(exportContainer);

      const link = document.createElement('a');
      link.download = `football-teams.${format}`;
      link.href = canvas.toDataURL(`image/${format}`, format === 'jpeg' ? 0.9 : undefined);
      link.click();
    } catch (error) {
      console.error('Error generating image:', error);
      alert('Error generating image. Please try again.');
    }
  };

  const copyToClipboard = async () => {
    const teams = [team1, team2, team3];
    let text = '⚽ FOOTBALL TEAMS ROSTER\n';
    text += `Generated on ${new Date().toLocaleDateString()}\n`;
    text += '=' .repeat(50) + '\n\n';

    teams.forEach((team) => {
      const avgRating = team.players.length > 0 
        ? (team.players.reduce((sum, p) => sum + (p.rating || 1), 0) / team.players.length).toFixed(1)
        : '0';
      
      text += `${team.name.toUpperCase()}\n`;
      text += `Players: ${team.players.length}/7 | Average Rating: ${avgRating}\n`;
      text += '-'.repeat(30) + '\n';
      
      if (team.players.length === 0) {
        text += 'No players assigned\n';
      } else {
        team.players.forEach((player, playerIndex) => {
          const stars = '★'.repeat(player.rating || 1) + '☆'.repeat(5 - (player.rating || 1));
          text += `${playerIndex + 1}. ${player.name} (${player.intra}) - ${stars}\n`;
        });
      }
      text += '\n';
    });

    text += '=' .repeat(50) + '\n';
    text += 'Generated by 42 Football Club Management System\n';

    try {
      await navigator.clipboard.writeText(text);
      alert('Teams roster copied to clipboard!');
    } catch (error) {
      console.error('Error copying to clipboard:', error);
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      alert('Teams roster copied to clipboard!');
    }
  };

  const updatePlayerRating = (playerId: string, rating: number) => {
    setAvailablePlayers(prev => 
      prev.map(player => 
        player.intra === playerId ? { ...player, rating } : player
      )
    );

    setTeam1(prev => ({
      ...prev,
      players: prev.players.map(player => 
        player.intra === playerId ? { ...player, rating } : player
      )
    }));

    setTeam2(prev => ({
      ...prev,
      players: prev.players.map(player => 
        player.intra === playerId ? { ...player, rating } : player
      )
    }));

    setTeam3(prev => ({
      ...prev,
      players: prev.players.map(player => 
        player.intra === playerId ? { ...player, rating } : player
      )
    }));
  };

  const StarRating = ({ rating, onRatingChange }: { rating: number, onRatingChange: (rating: number) => void }) => {
    return (
      <div className="star-rating">
        {[1, 2, 3, 4, 5].map((star) => (
          <span
            key={star}
            onClick={() => onRatingChange(star)}
            style={{
              color: star <= rating ? '#FFD700' : '#ccc',
            }}
          >
            ★
          </span>
        ))}
      </div>
    );
  };

  const handleDragStart = (e: React.DragEvent, player: User, source: 'available' | 'team1' | 'team2' | 'team3') => {
    setDraggedPlayer(player);
    setDragSource(source);
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };

  const handleDrop = (e: React.DragEvent, target: 'available' | 'team1' | 'team2' | 'team3') => {
    e.preventDefault();

    if (!draggedPlayer || !dragSource || dragSource === target) {
      return;
    }

    // Remove from source
    if (dragSource === 'available') {
      setAvailablePlayers(prev => prev.filter(p => p.intra !== draggedPlayer.intra));
    } else if (dragSource === 'team1') {
      setTeam1(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== draggedPlayer.intra) }));
    } else if (dragSource === 'team2') {
      setTeam2(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== draggedPlayer.intra) }));
    } else if (dragSource === 'team3') {
      setTeam3(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== draggedPlayer.intra) }));
    }

    // Add to target
    if (target === 'available') {
      setAvailablePlayers(prev => [...prev, draggedPlayer]);
    } else if (target === 'team1' && team1.players.length < 7) {
      setTeam1(prev => ({ ...prev, players: [...prev.players, draggedPlayer] }));
    } else if (target === 'team2' && team2.players.length < 7) {
      setTeam2(prev => ({ ...prev, players: [...prev.players, draggedPlayer] }));
    } else if (target === 'team3' && team3.players.length < 7) {
      setTeam3(prev => ({ ...prev, players: [...prev.players, draggedPlayer] }));
    }

    setDraggedPlayer(null);
    setDragSource(null);
  };

  const addToTeam = (player: User, teamNumber: 1 | 2 | 3) => {
    const targetTeam = teamNumber === 1 ? team1 : teamNumber === 2 ? team2 : team3;

    if (targetTeam.players.length >= 7) {
      return;
    }

    if (teamNumber === 1) {
      setTeam1(prev => ({ ...prev, players: [...prev.players, player] }));
    } else if (teamNumber === 2) {
      setTeam2(prev => ({ ...prev, players: [...prev.players, player] }));
    } else {
      setTeam3(prev => ({ ...prev, players: [...prev.players, player] }));
    }
    setAvailablePlayers(prev => prev.filter(p => p.intra !== player.intra));
  };

  const removeFromTeam = (player: User, teamNumber: 1 | 2 | 3) => {
    if (teamNumber === 1) {
      setTeam1(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== player.intra) }));
    } else if (teamNumber === 2) {
      setTeam2(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== player.intra) }));
    } else {
      setTeam3(prev => ({ ...prev, players: prev.players.filter(p => p.intra !== player.intra) }));
    }
    setAvailablePlayers(prev => [...prev, player]);
  };

  const autoBalance = () => {
    const allEligiblePlayers = [...availablePlayers, ...team1.players, ...team2.players, ...team3.players];
    const sortedPlayers = allEligiblePlayers.sort((a, b) => (b.rating || 1) - (a.rating || 1));

    const teams: User[][] = [[], [], []];

	const randomfirstpick = Math.floor(Math.random() * 3);

    const pickOrder: number[] = [];
    for (let round = 0; round < 7; round++) {
      if (round % 2 === 0) {
        pickOrder.push(randomfirstpick, (randomfirstpick + 1) % 3, (randomfirstpick + 2) % 3);
      } else {
        pickOrder.push((randomfirstpick + 2) % 3, (randomfirstpick + 1) % 3, randomfirstpick);
      }
    }

    // Assign players using snake draft order
    sortedPlayers.slice(0, 21).forEach((player, index) => {
      const teamIndex = pickOrder[index];
      teams[teamIndex].push(player);
    });

    const remainingPlayers = allEligiblePlayers.slice(21);

    setTeam1({ name: team1.name, players: teams[0] });
    setTeam2({ name: team2.name, players: teams[1] });
    setTeam3({ name: team3.name, players: teams[2] });
    setAvailablePlayers(remainingPlayers);
  };

  const removeFromEligible = (playerId: string) => {
    const removedPlayer = availablePlayers.find(p => p.intra === playerId);
    if (!removedPlayer) return;

    const updatedAvailable = availablePlayers.filter(p => p.intra !== playerId);
    setRemovedPlayers(prev => [...prev, removedPlayer]);

    if (waitingListPlayers.length > 0) {
      const nextPlayer = waitingListPlayers[0];
      const promotedPlayer = { ...nextPlayer, rating: 1 };

      setAvailablePlayers([...updatedAvailable, promotedPlayer]);
      setWaitingListPlayers(prev => prev.slice(1));
    } else {
      setAvailablePlayers(updatedAvailable);
    }
  };

  const restoreRemovedPlayer = (playerId: string) => {
    const playerToRestore = removedPlayers.find(p => p.intra === playerId);
    if (!playerToRestore) return;

    setRemovedPlayers(prev => prev.filter(p => p.intra !== playerId));

    if (availablePlayers.length >= GuaranteedSpot) {
      const playerToWaitingList = availablePlayers[availablePlayers.length - 1];
      setWaitingListPlayers(prev => [playerToWaitingList, ...prev]);
      setAvailablePlayers(prev => [...prev.slice(0, -1), playerToRestore]);
    } else {
      setAvailablePlayers(prev => [...prev, playerToRestore]);
    }
  };

  const clearTeams = () => {
    const allCurrentPlayers = [...availablePlayers, ...team1.players, ...team2.players, ...team3.players];
    const ratingMap = new Map();
    allCurrentPlayers.forEach(player => {
      ratingMap.set(player.intra, player.rating || 1);
    });

    const verifiedPlayers = registeredUsers.filter(user => user);
    const eligiblePlayers = verifiedPlayers.slice(0, GuaranteedSpot).map(user => ({ 
      ...user, 
      rating: ratingMap.get(user.intra) || 1 
    }));

    setAvailablePlayers(eligiblePlayers);
    setTeam1({ name: "Team 1", players: [] });
    setTeam2({ name: "Team 2", players: [] });
    setTeam3({ name: "Team 3", players: [] });
    setRemovedPlayers([]);
  };

  const updateTeamName = (teamNumber: 1 | 2 | 3, newName: string) => {
    if (teamNumber === 1) {
      setTeam1(prev => ({ ...prev, name: newName }));
    } else if (teamNumber === 2) {
      setTeam2(prev => ({ ...prev, name: newName }));
    } else {
      setTeam3(prev => ({ ...prev, name: newName }));
    }
  };

  const PlayerCard = ({ player, index, source, showTeamButtons = false }: { 
    player: User; 
    index: number; 
    source: 'available' | 'team1' | 'team2' | 'team3';
    showTeamButtons?: boolean;
  }) => (
    <div
      className="player-card"
      draggable
      onDragStart={(e) => handleDragStart(e, player, source)}
    >
      <div className="player-info">
        <span className="player-name">
          {index >= 0 && `${index + 1}. `}{player.name} ({player.intra})
        </span>
        <div className="player-actions">
          <StarRating 
            rating={player.rating || 1} 
            onRatingChange={(rating) => updatePlayerRating(player.intra, rating)}
          />
          {source === 'available' && (
            <button
              className="icon-button"
              onClick={() => removeFromEligible(player.intra)}
              title="Remove from eligible players"
            >
              🗑️
            </button>
          )}
          {source !== 'available' && (
            <button
              className="icon-button"
              onClick={() => removeFromTeam(player, source === 'team1' ? 1 : source === 'team2' ? 2 : 3)}
              title="Remove from team"
            >
              ❌
            </button>
          )}
        </div>
      </div>
      {showTeamButtons && (
        <div className="team-buttons">
          <button
            className="team-button team1"
            onClick={() => addToTeam(player, 1)}
            disabled={team1.players.length >= 7}
            title="Add to Team 1"
          >
            <span>🟦</span> T1 {team1.players.length >= 7 ? '(Full)' : ''}
          </button>
          <button
            className="team-button team2"
            onClick={() => addToTeam(player, 2)}
            disabled={team2.players.length >= 7}
            title="Add to Team 2"
          >
            <span>🟩</span> T2 {team2.players.length >= 7 ? '(Full)' : ''}
          </button>
          <button
            className="team-button team3"
            onClick={() => addToTeam(player, 3)}
            disabled={team3.players.length >= 7}
            title="Add to Team 3"
          >
            <span>🟨</span> T3 {team3.players.length >= 7 ? '(Full)' : ''}
          </button>
        </div>
      )}
    </div>
  );

  if (loading) {
    return (
      <>
        <Navbar />
        <div className="teams-container">
          <div className="teams-header">
            <h1>Team Selection</h1>
            <div className="loading-state">Loading players...</div>
          </div>
        </div>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Navbar />
      <div className="teams-container">
        <div className="teams-header">
          <h1>Team Selection (3 Teams of 7)</h1>
          <div className="teams-controls">
            <button onClick={autoBalance}>
              ⚖️ Auto Balance Teams
            </button>
            <button onClick={clearTeams}>
              🗑️ Clear All Teams
            </button>
            <div className="export-dropdown">
              <button 
                onClick={() => setShowExportMenu(!showExportMenu)}
                className="export-button"
              >
                📤 Export Teams
              </button>
              {showExportMenu && (
                <div className="export-menu">
                  <button onClick={exportToPDF}>
                    📄 Export as PDF
                  </button>
                  <button onClick={() => exportToImage('png')}>
                    🖼️ Export as PNG
                  </button>
                  <button onClick={() => exportToImage('jpeg')}>
                    🖼️ Export as JPEG
                  </button>
                  <button onClick={copyToClipboard}>
                    📋 Copy to Clipboard
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="teams-grid">
          {/* Available Players */}
          <div 
            className="team-card available-players"
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, 'available')}
          >
            <div className="team-header">
              <h3>Available Players ({availablePlayers.length})</h3>
            </div>
            <div className="player-list">
              {availablePlayers.length === 0 ? (
                <div className="empty-state">
                  All eligible players assigned to teams
                </div>
              ) : (
                availablePlayers.map((player, index) => (
                  <PlayerCard 
                    key={player.intra} 
                    player={player} 
                    index={index} 
                    source="available"
                    showTeamButtons={true}
                  />
                ))
              )}
            </div>
          </div>

          {/* Team 1 */}
          <div 
            className="team-card team1-players"
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, 'team1')}
          >
            <div className="team-header">
              <input
                type="text"
                value={team1.name}
                onChange={(e) => updateTeamName(1, e.target.value)}
                className="team-name-input"
                placeholder="Team 1 Name"
              />
              <span className="team-count">({team1.players.length}/7)</span>
            </div>
            <div className="player-list">
              {team1.players.length === 0 ? (
                <div className="empty-state">
                  Drag players here or use buttons
                </div>
              ) : (
                team1.players.map((player, index) => (
                  <PlayerCard 
                    key={player.intra} 
                    player={player} 
                    index={index} 
                    source="team1"
                  />
                ))
              )}
            </div>
          </div>

          {/* Team 2 */}
          <div 
            className="team-card team2-players"
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, 'team2')}
          >
            <div className="team-header">
              <input
                type="text"
                value={team2.name}
                onChange={(e) => updateTeamName(2, e.target.value)}
                className="team-name-input"
                placeholder="Team 2 Name"
              />
              <span className="team-count">({team2.players.length}/7)</span>
            </div>
            <div className="player-list">
              {team2.players.length === 0 ? (
                <div className="empty-state">
                  Drag players here or use buttons
                </div>
              ) : (
                team2.players.map((player, index) => (
                  <PlayerCard 
                    key={player.intra} 
                    player={player} 
                    index={index} 
                    source="team2"
                  />
                ))
              )}
            </div>
          </div>

          {/* Team 3 */}
          <div 
            className="team-card team3-players"
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, 'team3')}
          >
            <div className="team-header">
              <input
                type="text"
                value={team3.name}
                onChange={(e) => updateTeamName(3, e.target.value)}
                className="team-name-input"
                placeholder="Team 3 Name"
              />
              <span className="team-count">({team3.players.length}/7)</span>
            </div>
            <div className="player-list">
              {team3.players.length === 0 ? (
                <div className="empty-state">
                  Drag players here or use buttons
                </div>
              ) : (
                team3.players.map((player, index) => (
                  <PlayerCard 
                    key={player.intra} 
                    player={player} 
                    index={index} 
                    source="team3"
                  />
                ))
              )}
            </div>
          </div>
        </div>

        {/* Removed Players Section */}
        {removedPlayers.length > 0 && (
          <div className="summary-card">
            <h3>Recently Removed Players ({removedPlayers.length})</h3>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
              Players removed from team selection (can be restored)
            </p>
            <div className="player-list" style={{ maxHeight: '200px' }}>
              {removedPlayers.map((player) => (
                <div key={player.intra} className="player-card">
                  <div className="player-info">
                    <span className="player-name">{player.name} ({player.intra})</span>
                    <button
                      className="icon-button"
                      onClick={() => restoreRemovedPlayer(player.intra)}
                      title="Restore player"
                    >
                      ↩️
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Waiting List */}
        {waitingListPlayers.length > 0 && (
          <div className="summary-card">
            <h3>Waiting List ({waitingListPlayers.length})</h3>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
              Players beyond the first 21 registered (not eligible for current game)
            </p>
            <div className="player-list" style={{ maxHeight: '200px' }}>
              {waitingListPlayers.map((player, index) => (
                <div key={player.intra} className="player-card">
                  <span className="player-name">
                    #{GuaranteedSpot + index + 1} {player.name} ({player.intra})
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Team Summary */}
        <div className="summary-card">
          <h3>Team Summary</h3>
          <div className="summary-grid">
            <div className="summary-item">
              <h4 style={{ color: 'var(--ft-primary)' }}>🟦 {team1.name}</h4>
              <p>{team1.players.length} players</p>
              <p>Avg Rating: {team1.players.length > 0 ? (team1.players.reduce((sum, p) => sum + (p.rating || 1), 0) / team1.players.length).toFixed(1) : '0'}</p>
            </div>
            <div className="summary-item">
              <h4 style={{ color: 'var(--ft-secondary)' }}>🟩 {team2.name}</h4>
              <p>{team2.players.length} players</p>
              <p>Avg Rating: {team2.players.length > 0 ? (team2.players.reduce((sum, p) => sum + (p.rating || 1), 0) / team2.players.length).toFixed(1) : '0'}</p>
            </div>
            <div className="summary-item">
              <h4 style={{ color: '#28a745' }}>🟨 {team3.name}</h4>
              <p>{team3.players.length} players</p>
              <p>Avg Rating: {team3.players.length > 0 ? (team3.players.reduce((sum, p) => sum + (p.rating || 1), 0) / team3.players.length).toFixed(1) : '0'}</p>
            </div>
            <div className="summary-item">
              <h4 style={{ color: 'var(--text-secondary)' }}>📋 Available</h4>
              <p>{availablePlayers.length} players</p>
            </div>
            {waitingListPlayers.length > 0 && (
              <div className="summary-item">
                <h4 style={{ color: 'var(--text-secondary)' }}>⏳ Waiting</h4>
                <p>{waitingListPlayers.length} players</p>
              </div>
            )}
            {removedPlayers.length > 0 && (
              <div className="summary-item">
                <h4 style={{ color: 'var(--ft-accent)' }}>🗑️ Removed</h4>
                <p>{removedPlayers.length} players</p>
              </div>
            )}
          </div>
        </div>
        
        {/* Hidden container for export generation */}
        <div ref={exportRef} style={{ display: 'none' }} />
      </div>
      <Footer />
    </>
  );
};

export default Teams;